### PR TITLE
Add bots.discordlabs.org

### PR DESCRIPTION
**Pull request by anishanne**
Added bots.discordlabs.org to the list of fallback bot lists.

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
Instead of just adding a single list, this should be updated with the latest data from botblock

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
This looks incredibly wrong. You've somehow wrapped the object in another object, and you're changing all the single quotes to be double quotes etc...

**Comment by T0TProduction** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 50
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/T0TProduction/BLAPI/pullRequest?prid=6077754&bid=19897654)

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
This diff still looks very very wrong, please match the existing formatting and only change what needs to change...

**Review by T0TProduction — APPROVED** [review]
LGTM now 🤔

**Review by MattIPv4 — APPROVED** [review]
Lgtm -- I guess legacy IDs might also need an update.

**Comment by T0TProduction** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/T0TProduction/BLAPI/pullRequest?prid=6077754&bid=19897654)

**Pull request merged**
