### PR TITLE
Update discordbots.org name

### PR DESCRIPTION
**Pull request by NightYoshi370**
It's now Top.GG

### CODE REVIEW

**Comment by MattIPv4** [comment]
The ID in BotBlock is still `discordbots.org` (https://botblock.org/lists/discordbots.org), so this change would be incorrect to make as this lib will also still be using `discordbots.org`.

**Comment by Andre601** [comment]
Also, discordbots.org is still a valid URL to use as the owner of top.gg stated it that they won't get rid of it any time soon.

**Comment by T0TProduction** [comment]
As mentioned above, this would break the library. We could add the new domain as an alternative input though. If you want to open a PR you're more than welcome.

**Comment by MattIPv4** [comment]
We're currently working on adding support for legacy IDs to BotBlock, which allow this to happen.

**Comment by T0TProduction** [comment]
Would still need to change the internal fallback list and logic though, because BLAPI doesnt solely rely on botblock, right?

**Comment by MattIPv4** [comment]
Correct, new internal logic to this lib would need to be added for the fallback system to support legacy ids.

But if you're passing through to botblock, we'll treat a legacy id as if it were a normal id and just convert it internally on our end.

**Pull request closed without merging**
